[package]
name    = "omni-renderer"
version.workspace = true
edition.workspace = true

[dependencies]
omni-core  = { path = "../omni-core" }
wgpu       = { workspace = true }
egui-wgpu  = { workspace = true }
bytemuck   = { workspace = true }
anyhow     = { workspace = true }
log        = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
] }
